name: "Notion2Github Workflow"
author: "Lucio Villa"
description: "Update your Github profile README from Notion"

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  notion_page_id:
    description: "The Notion page ID."
    required: true
    default: ${{ secrets.NOTION_PAGE_ID }}
  notion_token:
    description: "The Notion API secret token"
    required: true
    default: ${{ secrets.NOTION_TOKEN }}
  committer_username:
    description: "Username used while committing to the repo"
    default: "notion2github-action"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "notion2github@example.com"
    required: false
  enable_keepalive:
    description: "Enables the feature that keeps the repo active by automatically committing to it even though there is no change"
    default: "true"
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: "activity"
  color: "blue"
