name: "Notion2Github Workflow"
author: "Lucio Villa"
description: "Update your Github profile README from Notion"

inputs:
  gh_token:
    description: 'GitHub access token with Repo scope'
    required: false
    default: ${{ github.token }}
  notion-token:
    description: 'Your Notion API Token'
    required: true
  notion-page-id:
    description: 'The Notion page id'
    required: true
  committer_username:
    description: "Username used while committing to the repo"
    default: "notion2github-action"
    required: false
  committer_email:
    description: "Email id used while committing to the repo"
    default: "notion2github@example.com"
    required: false
  commit_message:
    description: "Commit message used for auto-committing to the repo"
    default: "Auto-updated with latest changes from Notion"
    required: false
runs:
  using: node16
  main: dist/index.js
branding:
  icon: "activity"
  color: "blue"
